// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Slack
{
    public static class LookupUser
    {
        public static Task<LookupUserResult> InvokeAsync(LookupUserArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<LookupUserResult>("slack:index:LookupUser", args ?? new LookupUserArgs(), options.WithVersion());
    }


    public sealed class LookupUserArgs : Pulumi.InvokeArgs
    {
        [Input("email", required: true)]
        public string Email { get; set; } = null!;

        public LookupUserArgs()
        {
        }
    }


    [OutputType]
    public sealed class LookupUserResult
    {
        public readonly Outputs.User User;

        [OutputConstructor]
        private LookupUserResult(Outputs.User user)
        {
            User = user;
        }
    }
}
