// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Slack.Outputs
{

    [OutputType]
    public sealed class User
    {
        public readonly string Email;
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private User(
            string email,

            string id,

            string name)
        {
            Email = email;
            Id = id;
            Name = name;
        }
    }
}
