# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .conversation import *
from .lookup_user import *
from .provider import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "slack",
  "mod": "index",
  "fqn": "pulumi_slack",
  "classes": {
   "slack:index:Conversation": "Conversation"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "slack",
  "token": "pulumi:providers:slack",
  "fqn": "pulumi_slack",
  "class": "Provider"
 }
]
"""
)
