// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Channel {
    id: string;
    isArchived: boolean;
    isPrivate: boolean;
    members?: string[];
    name: string;
    purpose?: string;
    topic?: string;
}

export interface User {
    email: string;
    id: string;
    name: string;
}

