name: master
"on":
  push:
    branches:
      - master
      - "feature-**"
    paths-ignore:
      - CHANGELOG.md
    tags-ignore:
      - v*
      - sdk/*
      - '**'
env:
  GO111MODULE: "on"
  PROVIDER: slack
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_sdk:
    name: buildSDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [1.16.x]
        language: [ nodejs, python, dotnet, go ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: ci-scripts
          repository: pulumi/scripts
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 3.0.0-rc.1
      - name: Build gen binaries
        run: make gen
      - name: Build Provider binary
        run: make provider
      - name: Create SDK
        with:
          run: make ${{ matrix.language }}_sdk
      # - name: Check worktree clean
      #   run: ./ci-scripts/ci/check-worktree-is-clean
      - name: Test Provider Library
        run: make test_provider
      - name: Compress SDK folder
        run: tar -zcf sdk/${{ matrix.language }}.tar.gz -C sdk/${{ matrix.language }} .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.language  }}-sdk.tar.gz
          path: ${{ github.workspace}}/sdk/${{ matrix.language }}.tar.gz
      - if: failure() && github.event_name == 'push'
        name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          author_name: Failure in running ${{ matrix.language }} tests
          fields: repo,commit,author,action
          status: ${{ job.status }}