// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function lookupUser(args: LookupUserArgs, opts?: pulumi.InvokeOptions): Promise<LookupUserResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("slack:index:LookupUser", {
        "email": args.email,
    }, opts);
}

export interface LookupUserArgs {
    email: string;
}

export interface LookupUserResult {
    readonly user: outputs.User;
}
